# Generated by Django 5.1.3 on 2024-11-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userfollows'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollows',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
