# Generated by Django 5.1.3 on 2024-12-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userfollows_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='review_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='review_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='review_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
